### ISSUE TITLE
[TODO] Location Plugin

### ISSUE THREAD

**Issue by mighty1231** [mighty1231/screpl#2]
**Description**
Enumerate or edit locations.
All the other apps would use Location App to choose, or edit locations

**Tasks**
- [x] Location view app
    - [x] Show locations to superuser
    - [x] Return chosen location to caller
    - [x] Call location editor
- [x] Single location editor app, given init param as location (1-255)
    - [x] Several ways to edit (point, side, entire)
    - [x] Change flag 

**Related branch**
`feature-locedit`

**Link to source code**
[module](/mighty1231/screpl/tree/feature-locedit/apps/location)

**Comment by mighty1231** [comment]
**detailed tasks on LocationEditorApp**
- [x] translation
- [x] move points
- [x] move sides
- [x] grid things

**Comment by mighty1231** [comment]
Closing issue, check #7

**Comment by mighty1231** [comment]
Reopen since #7 solved
Currently there is no branch assigned for this issue.
