### ISSUE TITLE
[TODO] Documentation

### ISSUE THREAD

**Issue by mighty1231** [mighty1231/screpl#4]
**Tasks**
- [x] Utility functions that applications may use
- [ ] Step by step tutorial developing my own app
- [ ] Contribute with creating an issue
- [x] New method to write euddraft project file ( playerID )
